import { useEffect, useState } from "react";
import Navbar from "../components/Navbar";

import {
  ResponsiveContainer,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
} from "recharts";

const Performance = () => {
  const [performanceData, setPerformanceData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const fetchBenchmark = async () => {
      try {
        const response = await fetch(
          "http://localhost:5000/api/benchmark",
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              schema: {
                name: "name",
                email: "email",
                age: "number",
                city: "city",
                country: "country",
              },
            }),
          }
        );

        if (!response.ok) {
          throw new Error("Benchmark request failed");
        }

        const data = await response.json();

        if (!data.success) {
          throw new Error(
            data.message || "Benchmark failed"
          );
        }

        const formattedData = data.results.map((item) => ({
          size: `${item.records / 1000}K`,

          batchTime: Number(
            item.batch.generationTime
          ),

          streamingTime: Number(
            item.streaming.generationTime
          ),

          batchMemory: Number(
            item.batch.memoryUsed
          ),

          streamingMemory: Number(
            item.streaming.memoryUsed
          ),

          batchThroughput: Number(
            item.batch.throughput
          ),

          streamingThroughput: Number(
            item.streaming.throughput
          ),
        }));

        setPerformanceData(formattedData);
      } catch (err) {
        console.error(
          "Performance Error:",
          err
        );

        setError(
          "Unable to load benchmark results."
        );
      } finally {
        setLoading(false);
      }
    };

    fetchBenchmark();
  }, []);

  const largest =
    performanceData[
      performanceData.length - 1
    ];

  const timeDifference = largest
    ? (
        ((largest.batchTime -
          largest.streamingTime) /
          largest.batchTime) *
        100
      ).toFixed(1)
    : "0";

  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <Navbar />

      <main className="px-6 py-12">
        <div className="mx-auto max-w-7xl">

          {/* ================= HEADER ================= */}

          <div className="mb-10">
            <p className="text-sm font-semibold uppercase tracking-widest text-purple-400">
              Performance Analysis
            </p>

            <h1 className="mt-2 text-4xl font-bold sm:text-5xl">
              Generation Performance
            </h1>

            <p className="mt-4 max-w-3xl text-slate-400">
              Compare batch and streaming approaches
              using benchmark results generated by the
              backend.
            </p>
          </div>

          {/* ================= LOADING ================= */}

          {loading && (
            <div className="rounded-2xl border border-slate-800 bg-slate-900 p-10 text-center">

              <p className="text-slate-400">
                Running benchmark...
              </p>

              <p className="mt-2 text-sm text-slate-500">
                Testing 1K, 5K and 10K records.
              </p>

            </div>
          )}

          {/* ================= ERROR ================= */}

          {!loading && error && (
            <div className="rounded-2xl border border-red-500/20 bg-red-500/5 p-6">

              <p className="text-red-400">
                {error}
              </p>

              <p className="mt-2 text-sm text-slate-500">
                Make sure the Node.js backend is
                running.
              </p>

            </div>
          )}

          {/* ================= RESULTS ================= */}

          {!loading &&
            !error &&
            performanceData.length > 0 && (
              <>

                {/* ================= SUMMARY CARDS ================= */}

                <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">

                  {/* Largest Dataset */}

                  <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6">

                    <p className="text-sm text-slate-400">
                      Largest Dataset
                    </p>

                    <h2 className="mt-2 text-3xl font-bold">
                      {largest.size}
                    </h2>

                    <p className="mt-2 text-xs text-slate-500">
                      Records tested
                    </p>

                  </div>

                  {/* Batch Time */}

                  <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6">

                    <p className="text-sm text-slate-400">
                      Batch Time
                    </p>

                    <h2 className="mt-2 text-3xl font-bold">
                      {largest.batchTime} ms
                    </h2>

                    <p className="mt-2 text-xs text-slate-500">
                      For {largest.size} records
                    </p>

                  </div>

                  {/* Streaming Time */}

                  <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6">

                    <p className="text-sm text-slate-400">
                      Streaming Time
                    </p>

                    <h2 className="mt-2 text-3xl font-bold">
                      {largest.streamingTime} ms
                    </h2>

                    <p className="mt-2 text-xs text-slate-500">
                      For {largest.size} records
                    </p>

                  </div>

                  {/* Streaming Memory */}

                  <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6">

                    <p className="text-sm text-slate-400">
                      Streaming Memory
                    </p>

                    <h2 className="mt-2 text-3xl font-bold">
                      {largest.streamingMemory} MB
                    </h2>

                    <p className="mt-2 text-xs text-slate-500">
                      Observed peak RSS delta
                    </p>

                  </div>

                </div>

                {/* ================= TIME + MEMORY CHARTS ================= */}

                <div className="mt-8 grid gap-8 lg:grid-cols-2">

                  {/* Generation Time */}

                  <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6">

                    <h2 className="text-xl font-semibold">
                      Generation Time Comparison
                    </h2>

                    <p className="mt-1 text-sm text-slate-400">
                      Batch vs Streaming execution time
                    </p>

                    <div className="mt-6 h-[350px] w-full">

                      <ResponsiveContainer
                        width="100%"
                        height="100%"
                      >

                        <LineChart
                          data={performanceData}
                        >

                          <CartesianGrid
                            strokeDasharray="3 3"
                          />

                          <XAxis
                            dataKey="size"
                            tick={{
                              fill: "#94a3b8",
                            }}
                          />

                          <YAxis
                            tick={{
                              fill: "#94a3b8",
                            }}
                          />

                          <Tooltip
                            contentStyle={{
                              backgroundColor:
                                "#0f172a",
                              border:
                                "1px solid #334155",
                              borderRadius:
                                "8px",
                            }}
                          />

                          <Legend />

                          <Line
                            type="monotone"
                            dataKey="batchTime"
                            name="Batch"
                            stroke="#a855f7"
                            strokeWidth={3}
                            dot={{ r: 5 }}
                          />

                          <Line
                            type="monotone"
                            dataKey="streamingTime"
                            name="Streaming"
                            stroke="#22c55e"
                            strokeWidth={3}
                            dot={{ r: 5 }}
                          />

                        </LineChart>

                      </ResponsiveContainer>

                    </div>

                  </div>

                  {/* Memory Usage */}

                  <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6">

                    <h2 className="text-xl font-semibold">
                      Memory Usage Comparison
                    </h2>

                    <p className="mt-1 text-sm text-slate-400">
                      Observed peak RSS memory delta
                    </p>

                    <div className="mt-6 h-[350px] w-full">

                      <ResponsiveContainer
                        width="100%"
                        height="100%"
                      >

                        <LineChart
                          data={performanceData}
                        >

                          <CartesianGrid
                            strokeDasharray="3 3"
                          />

                          <XAxis
                            dataKey="size"
                            tick={{
                              fill: "#94a3b8",
                            }}
                          />

                          <YAxis
                            tick={{
                              fill: "#94a3b8",
                            }}
                          />

                          <Tooltip
                            contentStyle={{
                              backgroundColor:
                                "#0f172a",
                              border:
                                "1px solid #334155",
                              borderRadius:
                                "8px",
                            }}
                          />

                          <Legend />

                          <Line
                            type="monotone"
                            dataKey="batchMemory"
                            name="Batch"
                            stroke="#a855f7"
                            strokeWidth={3}
                            dot={{ r: 5 }}
                          />

                          <Line
                            type="monotone"
                            dataKey="streamingMemory"
                            name="Streaming"
                            stroke="#22c55e"
                            strokeWidth={3}
                            dot={{ r: 5 }}
                          />

                        </LineChart>

                      </ResponsiveContainer>

                    </div>

                  </div>

                </div>

                {/* ================= THROUGHPUT CHART ================= */}

                <div className="mt-8 rounded-2xl border border-slate-800 bg-slate-900 p-6">

                  <h2 className="text-xl font-semibold">
                    Throughput Comparison
                  </h2>

                  <p className="mt-1 text-sm text-slate-400">
                    Number of records generated per second
                  </p>

                  <div className="mt-6 h-[350px] w-full">

                    <ResponsiveContainer
                      width="100%"
                      height="100%"
                    >

                      <LineChart
                        data={performanceData}
                      >

                        <CartesianGrid
                          strokeDasharray="3 3"
                        />

                        <XAxis
                          dataKey="size"
                          tick={{
                            fill: "#94a3b8",
                          }}
                        />

                        <YAxis
                          tick={{
                            fill: "#94a3b8",
                          }}
                        />

                        <Tooltip
                          contentStyle={{
                            backgroundColor:
                              "#0f172a",
                            border:
                              "1px solid #334155",
                            borderRadius:
                              "8px",
                          }}
                        />

                        <Legend />

                        <Line
                          type="monotone"
                          dataKey="batchThroughput"
                          name="Batch"
                          stroke="#a855f7"
                          strokeWidth={3}
                          dot={{ r: 5 }}
                        />

                        <Line
                          type="monotone"
                          dataKey="streamingThroughput"
                          name="Streaming"
                          stroke="#22c55e"
                          strokeWidth={3}
                          dot={{ r: 5 }}
                        />

                      </LineChart>

                    </ResponsiveContainer>

                  </div>

                </div>

                {/* ================= TABLE ================= */}

                <div className="mt-8 rounded-2xl border border-slate-800 bg-slate-900 p-6">

                  <h2 className="text-xl font-semibold">
                    Benchmark Results
                  </h2>

                  <p className="mt-1 text-sm text-slate-400">
                    Results generated automatically by
                    the backend.
                  </p>

                  <div className="mt-6 overflow-x-auto">

                    <table className="w-full min-w-275 text-left">

                      <thead>

                        <tr className="border-b border-slate-800 text-sm text-slate-400">

                          <th className="px-4 py-4 font-medium">
                            Dataset
                          </th>

                          <th className="px-4 py-4 font-medium">
                            Batch Time
                          </th>

                          <th className="px-4 py-4 font-medium">
                            Streaming Time
                          </th>

                          <th className="px-4 py-4 font-medium">
                            Batch Memory
                          </th>

                          <th className="px-4 py-4 font-medium">
                            Streaming Memory
                          </th>

                          <th className="px-4 py-4 font-medium">
                            Batch Throughput
                          </th>

                          <th className="px-4 py-4 font-medium">
                            Streaming Throughput
                          </th>

                        </tr>

                      </thead>

                      <tbody>

                        {performanceData.map(
                          (item, index) => (
                            <tr
                              key={index}
                              className="border-b border-slate-800 last:border-0"
                            >

                              <td className="px-4 py-5 font-semibold">
                                {item.size}
                              </td>

                              <td className="px-4 py-5 text-slate-300">
                                {item.batchTime} ms
                              </td>

                              <td className="px-4 py-5 text-slate-300">
                                {item.streamingTime} ms
                              </td>

                              <td className="px-4 py-5 text-slate-300">
                                {item.batchMemory} MB
                              </td>

                              <td className="px-4 py-5 text-slate-300">
                                {item.streamingMemory} MB
                              </td>

                              <td className="px-4 py-5 text-slate-300">
                                {item.batchThroughput} records/s
                              </td>

                              <td className="px-4 py-5 text-slate-300">
                                {item.streamingThroughput} records/s
                              </td>

                            </tr>
                          )
                        )}

                      </tbody>

                    </table>

                  </div>

                </div>

                {/* ================= KEY OBSERVATION ================= */}

                <div className="mt-8 rounded-2xl border border-slate-800 bg-slate-900 p-6">

                  <h2 className="text-xl font-semibold">
                    Key Observation
                  </h2>

                  <p className="mt-4 text-sm leading-7 text-slate-400">

                    For the{" "}

                    <span className="font-semibold text-white">
                      {largest.size}
                    </span>{" "}

                    benchmark, streaming completed
                    generation in{" "}

                    <span className="font-semibold text-white">
                      {largest.streamingTime} ms
                    </span>{" "}

                    compared with{" "}

                    <span className="font-semibold text-white">
                      {largest.batchTime} ms
                    </span>{" "}

                    for batch generation.

                  </p>

                  <p className="mt-3 text-sm leading-7 text-slate-400">

                    Streaming showed approximately{" "}

                    <span className="font-semibold text-purple-400">
                      {timeDifference}%
                    </span>{" "}

                    lower generation time in this
                    particular benchmark.

                  </p>

                  <p className="mt-3 text-sm leading-7 text-slate-400">

                    Memory values represent observed peak
                    RSS differences and may vary because
                    of Node.js runtime allocation and
                    garbage collection.

                  </p>

                </div>

                {/* ================= RESEARCH NOTE ================= */}

                <div className="mt-8 rounded-xl border border-purple-500/20 bg-purple-500/5 p-5">

                  <div className="flex gap-3">

                    <span className="text-purple-400">
                      ℹ
                    </span>

                    <p className="text-sm leading-6 text-slate-400">

                      <span className="font-semibold text-purple-400">
                        Research Note:
                      </span>{" "}

                      Benchmark results are generated
                      dynamically from the Node.js backend
                      using the current implementation.
                      Results may vary between executions
                      depending on the test environment.

                    </p>

                  </div>

                </div>

              </>
            )}

        </div>
      </main>
    </div>
  );
};

export default Performance;